/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrunlerRouteImport } from './routes/urunler'
import { Route as RuRouteImport } from './routes/ru'
import { Route as ReferanslarRouteImport } from './routes/referanslar'
import { Route as ProjelerRouteImport } from './routes/projeler'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as GizlilikPolitikasiRouteImport } from './routes/gizlilik-politikasi'
import { Route as EnRouteImport } from './routes/en'
import { Route as CerezPolitikasiRouteImport } from './routes/cerez-politikasi'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UrunlerIndexRouteImport } from './routes/urunler.index'
import { Route as RuIndexRouteImport } from './routes/ru/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UrunlerSlugRouteImport } from './routes/urunler.$slug'
import { Route as RuProductsRouteImport } from './routes/ru/products'
import { Route as RuPortfolioRouteImport } from './routes/ru/portfolio'
import { Route as RuContactRouteImport } from './routes/ru/contact'
import { Route as RuBlogRouteImport } from './routes/ru/blog'
import { Route as RuAboutRouteImport } from './routes/ru/about'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as EnProductsRouteImport } from './routes/en/products'
import { Route as EnPortfolioRouteImport } from './routes/en/portfolio'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnBlogRouteImport } from './routes/en/blog'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProtectedRouteImport } from './routes/admin._protected'
import { Route as AdminProtectedIndexRouteImport } from './routes/admin._protected.index'
import { Route as RuProductsSlugRouteImport } from './routes/ru/products.$slug'
import { Route as RuPortfolioSlugRouteImport } from './routes/ru/portfolio.$slug'
import { Route as RuBlogSlugRouteImport } from './routes/ru/blog.$slug'
import { Route as EnProductsSlugRouteImport } from './routes/en/products.$slug'
import { Route as EnPortfolioSlugRouteImport } from './routes/en/portfolio.$slug'
import { Route as EnBlogSlugRouteImport } from './routes/en/blog.$slug'
import { Route as AdminProtectedSettingsRouteImport } from './routes/admin._protected.settings'
import { Route as AdminProtectedProductsRouteImport } from './routes/admin._protected.products'
import { Route as AdminProtectedLeadsRouteImport } from './routes/admin._protected.leads'
import { Route as AdminProtectedDashboardRouteImport } from './routes/admin._protected.dashboard'

const UrunlerRoute = UrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferanslarRoute = ReferanslarRouteImport.update({
  id: '/referanslar',
  path: '/referanslar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerRoute = ProjelerRouteImport.update({
  id: '/projeler',
  path: '/projeler',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikPolitikasiRoute = GizlilikPolitikasiRouteImport.update({
  id: '/gizlilik-politikasi',
  path: '/gizlilik-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const CerezPolitikasiRoute = CerezPolitikasiRouteImport.update({
  id: '/cerez-politikasi',
  path: '/cerez-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerIndexRoute = UrunlerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UrunlerRoute,
} as any)
const RuIndexRoute = RuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RuRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const UrunlerSlugRoute = UrunlerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UrunlerRoute,
} as any)
const RuProductsRoute = RuProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => RuRoute,
} as any)
const RuPortfolioRoute = RuPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => RuRoute,
} as any)
const RuContactRoute = RuContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => RuRoute,
} as any)
const RuBlogRoute = RuBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => RuRoute,
} as any)
const RuAboutRoute = RuAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => RuRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const EnProductsRoute = EnProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => EnRoute,
} as any)
const EnPortfolioRoute = EnPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => EnRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRoute,
} as any)
const EnBlogRoute = EnBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProtectedRoute = AdminProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProtectedIndexRoute = AdminProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const RuProductsSlugRoute = RuProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuProductsRoute,
} as any)
const RuPortfolioSlugRoute = RuPortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuPortfolioRoute,
} as any)
const RuBlogSlugRoute = RuBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuBlogRoute,
} as any)
const EnProductsSlugRoute = EnProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnProductsRoute,
} as any)
const EnPortfolioSlugRoute = EnPortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnPortfolioRoute,
} as any)
const EnBlogSlugRoute = EnBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnBlogRoute,
} as any)
const AdminProtectedSettingsRoute = AdminProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedProductsRoute = AdminProtectedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedLeadsRoute = AdminProtectedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedDashboardRoute = AdminProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/en': typeof EnRouteWithChildren
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/projeler': typeof ProjelerRoute
  '/referanslar': typeof ReferanslarRoute
  '/ru': typeof RuRouteWithChildren
  '/urunler': typeof UrunlerRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRouteWithChildren
  '/en/products': typeof EnProductsRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/blog': typeof RuBlogRouteWithChildren
  '/ru/contact': typeof RuContactRoute
  '/ru/portfolio': typeof RuPortfolioRouteWithChildren
  '/ru/products': typeof RuProductsRouteWithChildren
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/en/': typeof EnIndexRoute
  '/ru/': typeof RuIndexRoute
  '/urunler/': typeof UrunlerIndexRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/leads': typeof AdminProtectedLeadsRoute
  '/admin/products': typeof AdminProtectedProductsRoute
  '/admin/settings': typeof AdminProtectedSettingsRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/portfolio/$slug': typeof EnPortfolioSlugRoute
  '/en/products/$slug': typeof EnProductsSlugRoute
  '/ru/blog/$slug': typeof RuBlogSlugRoute
  '/ru/portfolio/$slug': typeof RuPortfolioSlugRoute
  '/ru/products/$slug': typeof RuProductsSlugRoute
  '/admin/': typeof AdminProtectedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedIndexRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/projeler': typeof ProjelerRoute
  '/referanslar': typeof ReferanslarRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRouteWithChildren
  '/en/products': typeof EnProductsRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/blog': typeof RuBlogRouteWithChildren
  '/ru/contact': typeof RuContactRoute
  '/ru/portfolio': typeof RuPortfolioRouteWithChildren
  '/ru/products': typeof RuProductsRouteWithChildren
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/blog': typeof BlogIndexRoute
  '/en': typeof EnIndexRoute
  '/ru': typeof RuIndexRoute
  '/urunler': typeof UrunlerIndexRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/leads': typeof AdminProtectedLeadsRoute
  '/admin/products': typeof AdminProtectedProductsRoute
  '/admin/settings': typeof AdminProtectedSettingsRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/portfolio/$slug': typeof EnPortfolioSlugRoute
  '/en/products/$slug': typeof EnProductsSlugRoute
  '/ru/blog/$slug': typeof RuBlogSlugRoute
  '/ru/portfolio/$slug': typeof RuPortfolioSlugRoute
  '/ru/products/$slug': typeof RuProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/en': typeof EnRouteWithChildren
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/projeler': typeof ProjelerRoute
  '/referanslar': typeof ReferanslarRoute
  '/ru': typeof RuRouteWithChildren
  '/urunler': typeof UrunlerRouteWithChildren
  '/admin/_protected': typeof AdminProtectedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRouteWithChildren
  '/en/products': typeof EnProductsRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/blog': typeof RuBlogRouteWithChildren
  '/ru/contact': typeof RuContactRoute
  '/ru/portfolio': typeof RuPortfolioRouteWithChildren
  '/ru/products': typeof RuProductsRouteWithChildren
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/en/': typeof EnIndexRoute
  '/ru/': typeof RuIndexRoute
  '/urunler/': typeof UrunlerIndexRoute
  '/admin/_protected/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/_protected/leads': typeof AdminProtectedLeadsRoute
  '/admin/_protected/products': typeof AdminProtectedProductsRoute
  '/admin/_protected/settings': typeof AdminProtectedSettingsRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/portfolio/$slug': typeof EnPortfolioSlugRoute
  '/en/products/$slug': typeof EnProductsSlugRoute
  '/ru/blog/$slug': typeof RuBlogSlugRoute
  '/ru/portfolio/$slug': typeof RuPortfolioSlugRoute
  '/ru/products/$slug': typeof RuProductsSlugRoute
  '/admin/_protected/': typeof AdminProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/cerez-politikasi'
    | '/en'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iletisim'
    | '/kvkk'
    | '/portfolio'
    | '/projeler'
    | '/referanslar'
    | '/ru'
    | '/urunler'
    | '/admin/login'
    | '/blog/$slug'
    | '/en/about'
    | '/en/blog'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/products'
    | '/portfolio/$slug'
    | '/ru/about'
    | '/ru/blog'
    | '/ru/contact'
    | '/ru/portfolio'
    | '/ru/products'
    | '/urunler/$slug'
    | '/blog/'
    | '/en/'
    | '/ru/'
    | '/urunler/'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/products'
    | '/admin/settings'
    | '/en/blog/$slug'
    | '/en/portfolio/$slug'
    | '/en/products/$slug'
    | '/ru/blog/$slug'
    | '/ru/portfolio/$slug'
    | '/ru/products/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cerez-politikasi'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iletisim'
    | '/kvkk'
    | '/portfolio'
    | '/projeler'
    | '/referanslar'
    | '/admin/login'
    | '/blog/$slug'
    | '/en/about'
    | '/en/blog'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/products'
    | '/portfolio/$slug'
    | '/ru/about'
    | '/ru/blog'
    | '/ru/contact'
    | '/ru/portfolio'
    | '/ru/products'
    | '/urunler/$slug'
    | '/blog'
    | '/en'
    | '/ru'
    | '/urunler'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/products'
    | '/admin/settings'
    | '/en/blog/$slug'
    | '/en/portfolio/$slug'
    | '/en/products/$slug'
    | '/ru/blog/$slug'
    | '/ru/portfolio/$slug'
    | '/ru/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/cerez-politikasi'
    | '/en'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iletisim'
    | '/kvkk'
    | '/portfolio'
    | '/projeler'
    | '/referanslar'
    | '/ru'
    | '/urunler'
    | '/admin/_protected'
    | '/admin/login'
    | '/blog/$slug'
    | '/en/about'
    | '/en/blog'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/products'
    | '/portfolio/$slug'
    | '/ru/about'
    | '/ru/blog'
    | '/ru/contact'
    | '/ru/portfolio'
    | '/ru/products'
    | '/urunler/$slug'
    | '/blog/'
    | '/en/'
    | '/ru/'
    | '/urunler/'
    | '/admin/_protected/dashboard'
    | '/admin/_protected/leads'
    | '/admin/_protected/products'
    | '/admin/_protected/settings'
    | '/en/blog/$slug'
    | '/en/portfolio/$slug'
    | '/en/products/$slug'
    | '/ru/blog/$slug'
    | '/ru/portfolio/$slug'
    | '/ru/products/$slug'
    | '/admin/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CerezPolitikasiRoute: typeof CerezPolitikasiRoute
  EnRoute: typeof EnRouteWithChildren
  GizlilikPolitikasiRoute: typeof GizlilikPolitikasiRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  KvkkRoute: typeof KvkkRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ProjelerRoute: typeof ProjelerRoute
  ReferanslarRoute: typeof ReferanslarRoute
  RuRoute: typeof RuRouteWithChildren
  UrunlerRoute: typeof UrunlerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urunler': {
      id: '/urunler'
      path: '/urunler'
      fullPath: '/urunler'
      preLoaderRoute: typeof UrunlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referanslar': {
      id: '/referanslar'
      path: '/referanslar'
      fullPath: '/referanslar'
      preLoaderRoute: typeof ReferanslarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeler': {
      id: '/projeler'
      path: '/projeler'
      fullPath: '/projeler'
      preLoaderRoute: typeof ProjelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik-politikasi': {
      id: '/gizlilik-politikasi'
      path: '/gizlilik-politikasi'
      fullPath: '/gizlilik-politikasi'
      preLoaderRoute: typeof GizlilikPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerez-politikasi': {
      id: '/cerez-politikasi'
      path: '/cerez-politikasi'
      fullPath: '/cerez-politikasi'
      preLoaderRoute: typeof CerezPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler/': {
      id: '/urunler/'
      path: '/'
      fullPath: '/urunler/'
      preLoaderRoute: typeof UrunlerIndexRouteImport
      parentRoute: typeof UrunlerRoute
    }
    '/ru/': {
      id: '/ru/'
      path: '/'
      fullPath: '/ru/'
      preLoaderRoute: typeof RuIndexRouteImport
      parentRoute: typeof RuRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/urunler/$slug': {
      id: '/urunler/$slug'
      path: '/$slug'
      fullPath: '/urunler/$slug'
      preLoaderRoute: typeof UrunlerSlugRouteImport
      parentRoute: typeof UrunlerRoute
    }
    '/ru/products': {
      id: '/ru/products'
      path: '/products'
      fullPath: '/ru/products'
      preLoaderRoute: typeof RuProductsRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/portfolio': {
      id: '/ru/portfolio'
      path: '/portfolio'
      fullPath: '/ru/portfolio'
      preLoaderRoute: typeof RuPortfolioRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/contact': {
      id: '/ru/contact'
      path: '/contact'
      fullPath: '/ru/contact'
      preLoaderRoute: typeof RuContactRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/blog': {
      id: '/ru/blog'
      path: '/blog'
      fullPath: '/ru/blog'
      preLoaderRoute: typeof RuBlogRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/about': {
      id: '/ru/about'
      path: '/about'
      fullPath: '/ru/about'
      preLoaderRoute: typeof RuAboutRouteImport
      parentRoute: typeof RuRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/en/products': {
      id: '/en/products'
      path: '/products'
      fullPath: '/en/products'
      preLoaderRoute: typeof EnProductsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/portfolio': {
      id: '/en/portfolio'
      path: '/portfolio'
      fullPath: '/en/portfolio'
      preLoaderRoute: typeof EnPortfolioRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/blog': {
      id: '/en/blog'
      path: '/blog'
      fullPath: '/en/blog'
      preLoaderRoute: typeof EnBlogRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_protected/': {
      id: '/admin/_protected/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminProtectedIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/ru/products/$slug': {
      id: '/ru/products/$slug'
      path: '/$slug'
      fullPath: '/ru/products/$slug'
      preLoaderRoute: typeof RuProductsSlugRouteImport
      parentRoute: typeof RuProductsRoute
    }
    '/ru/portfolio/$slug': {
      id: '/ru/portfolio/$slug'
      path: '/$slug'
      fullPath: '/ru/portfolio/$slug'
      preLoaderRoute: typeof RuPortfolioSlugRouteImport
      parentRoute: typeof RuPortfolioRoute
    }
    '/ru/blog/$slug': {
      id: '/ru/blog/$slug'
      path: '/$slug'
      fullPath: '/ru/blog/$slug'
      preLoaderRoute: typeof RuBlogSlugRouteImport
      parentRoute: typeof RuBlogRoute
    }
    '/en/products/$slug': {
      id: '/en/products/$slug'
      path: '/$slug'
      fullPath: '/en/products/$slug'
      preLoaderRoute: typeof EnProductsSlugRouteImport
      parentRoute: typeof EnProductsRoute
    }
    '/en/portfolio/$slug': {
      id: '/en/portfolio/$slug'
      path: '/$slug'
      fullPath: '/en/portfolio/$slug'
      preLoaderRoute: typeof EnPortfolioSlugRouteImport
      parentRoute: typeof EnPortfolioRoute
    }
    '/en/blog/$slug': {
      id: '/en/blog/$slug'
      path: '/$slug'
      fullPath: '/en/blog/$slug'
      preLoaderRoute: typeof EnBlogSlugRouteImport
      parentRoute: typeof EnBlogRoute
    }
    '/admin/_protected/settings': {
      id: '/admin/_protected/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminProtectedSettingsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/products': {
      id: '/admin/_protected/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProtectedProductsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/leads': {
      id: '/admin/_protected/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminProtectedLeadsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/dashboard': {
      id: '/admin/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminProtectedDashboardRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
  }
}

interface AdminProtectedRouteChildren {
  AdminProtectedDashboardRoute: typeof AdminProtectedDashboardRoute
  AdminProtectedLeadsRoute: typeof AdminProtectedLeadsRoute
  AdminProtectedProductsRoute: typeof AdminProtectedProductsRoute
  AdminProtectedSettingsRoute: typeof AdminProtectedSettingsRoute
  AdminProtectedIndexRoute: typeof AdminProtectedIndexRoute
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedDashboardRoute: AdminProtectedDashboardRoute,
  AdminProtectedLeadsRoute: AdminProtectedLeadsRoute,
  AdminProtectedProductsRoute: AdminProtectedProductsRoute,
  AdminProtectedSettingsRoute: AdminProtectedSettingsRoute,
  AdminProtectedIndexRoute: AdminProtectedIndexRoute,
}

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
)

interface AdminRouteChildren {
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EnBlogRouteChildren {
  EnBlogSlugRoute: typeof EnBlogSlugRoute
}

const EnBlogRouteChildren: EnBlogRouteChildren = {
  EnBlogSlugRoute: EnBlogSlugRoute,
}

const EnBlogRouteWithChildren =
  EnBlogRoute._addFileChildren(EnBlogRouteChildren)

interface EnPortfolioRouteChildren {
  EnPortfolioSlugRoute: typeof EnPortfolioSlugRoute
}

const EnPortfolioRouteChildren: EnPortfolioRouteChildren = {
  EnPortfolioSlugRoute: EnPortfolioSlugRoute,
}

const EnPortfolioRouteWithChildren = EnPortfolioRoute._addFileChildren(
  EnPortfolioRouteChildren,
)

interface EnProductsRouteChildren {
  EnProductsSlugRoute: typeof EnProductsSlugRoute
}

const EnProductsRouteChildren: EnProductsRouteChildren = {
  EnProductsSlugRoute: EnProductsSlugRoute,
}

const EnProductsRouteWithChildren = EnProductsRoute._addFileChildren(
  EnProductsRouteChildren,
)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnBlogRoute: typeof EnBlogRouteWithChildren
  EnContactRoute: typeof EnContactRoute
  EnPortfolioRoute: typeof EnPortfolioRouteWithChildren
  EnProductsRoute: typeof EnProductsRouteWithChildren
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnBlogRoute: EnBlogRouteWithChildren,
  EnContactRoute: EnContactRoute,
  EnPortfolioRoute: EnPortfolioRouteWithChildren,
  EnProductsRoute: EnProductsRouteWithChildren,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface RuBlogRouteChildren {
  RuBlogSlugRoute: typeof RuBlogSlugRoute
}

const RuBlogRouteChildren: RuBlogRouteChildren = {
  RuBlogSlugRoute: RuBlogSlugRoute,
}

const RuBlogRouteWithChildren =
  RuBlogRoute._addFileChildren(RuBlogRouteChildren)

interface RuPortfolioRouteChildren {
  RuPortfolioSlugRoute: typeof RuPortfolioSlugRoute
}

const RuPortfolioRouteChildren: RuPortfolioRouteChildren = {
  RuPortfolioSlugRoute: RuPortfolioSlugRoute,
}

const RuPortfolioRouteWithChildren = RuPortfolioRoute._addFileChildren(
  RuPortfolioRouteChildren,
)

interface RuProductsRouteChildren {
  RuProductsSlugRoute: typeof RuProductsSlugRoute
}

const RuProductsRouteChildren: RuProductsRouteChildren = {
  RuProductsSlugRoute: RuProductsSlugRoute,
}

const RuProductsRouteWithChildren = RuProductsRoute._addFileChildren(
  RuProductsRouteChildren,
)

interface RuRouteChildren {
  RuAboutRoute: typeof RuAboutRoute
  RuBlogRoute: typeof RuBlogRouteWithChildren
  RuContactRoute: typeof RuContactRoute
  RuPortfolioRoute: typeof RuPortfolioRouteWithChildren
  RuProductsRoute: typeof RuProductsRouteWithChildren
  RuIndexRoute: typeof RuIndexRoute
}

const RuRouteChildren: RuRouteChildren = {
  RuAboutRoute: RuAboutRoute,
  RuBlogRoute: RuBlogRouteWithChildren,
  RuContactRoute: RuContactRoute,
  RuPortfolioRoute: RuPortfolioRouteWithChildren,
  RuProductsRoute: RuProductsRouteWithChildren,
  RuIndexRoute: RuIndexRoute,
}

const RuRouteWithChildren = RuRoute._addFileChildren(RuRouteChildren)

interface UrunlerRouteChildren {
  UrunlerSlugRoute: typeof UrunlerSlugRoute
  UrunlerIndexRoute: typeof UrunlerIndexRoute
}

const UrunlerRouteChildren: UrunlerRouteChildren = {
  UrunlerSlugRoute: UrunlerSlugRoute,
  UrunlerIndexRoute: UrunlerIndexRoute,
}

const UrunlerRouteWithChildren =
  UrunlerRoute._addFileChildren(UrunlerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CerezPolitikasiRoute: CerezPolitikasiRoute,
  EnRoute: EnRouteWithChildren,
  GizlilikPolitikasiRoute: GizlilikPolitikasiRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  KvkkRoute: KvkkRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  ProjelerRoute: ProjelerRoute,
  ReferanslarRoute: ReferanslarRoute,
  RuRoute: RuRouteWithChildren,
  UrunlerRoute: UrunlerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
