/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProtectedRouteImport } from './routes/admin._protected'
import { Route as AdminProtectedIndexRouteImport } from './routes/admin._protected.index'
import { Route as AdminProtectedProductsRouteImport } from './routes/admin._protected.products'
import { Route as AdminProtectedLeadsRouteImport } from './routes/admin._protected.leads'
import { Route as AdminProtectedDashboardRouteImport } from './routes/admin._protected.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedRoute = AdminProtectedRouteImport.update({
  id: '/admin/_protected',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedIndexRoute = AdminProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedProductsRoute = AdminProtectedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedLeadsRoute = AdminProtectedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedDashboardRoute = AdminProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/leads': typeof AdminProtectedLeadsRoute
  '/admin/products': typeof AdminProtectedProductsRoute
  '/admin/': typeof AdminProtectedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/leads': typeof AdminProtectedLeadsRoute
  '/admin/products': typeof AdminProtectedProductsRoute
  '/admin': typeof AdminProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_protected': typeof AdminProtectedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_protected/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/_protected/leads': typeof AdminProtectedLeadsRoute
  '/admin/_protected/products': typeof AdminProtectedProductsRoute
  '/admin/_protected/': typeof AdminProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/products'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/products'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/_protected'
    | '/admin/login'
    | '/admin/_protected/dashboard'
    | '/admin/_protected/leads'
    | '/admin/_protected/products'
    | '/admin/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected/': {
      id: '/admin/_protected/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminProtectedIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/products': {
      id: '/admin/_protected/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProtectedProductsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/leads': {
      id: '/admin/_protected/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminProtectedLeadsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/dashboard': {
      id: '/admin/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminProtectedDashboardRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
  }
}

interface AdminProtectedRouteChildren {
  AdminProtectedDashboardRoute: typeof AdminProtectedDashboardRoute
  AdminProtectedLeadsRoute: typeof AdminProtectedLeadsRoute
  AdminProtectedProductsRoute: typeof AdminProtectedProductsRoute
  AdminProtectedIndexRoute: typeof AdminProtectedIndexRoute
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedDashboardRoute: AdminProtectedDashboardRoute,
  AdminProtectedLeadsRoute: AdminProtectedLeadsRoute,
  AdminProtectedProductsRoute: AdminProtectedProductsRoute,
  AdminProtectedIndexRoute: AdminProtectedIndexRoute,
}

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
